// MyMelvorNg/src/app/cooking/cooking.component.ts
import { Component, inject } from '@angular/core';
import { PlayerService } from '../player.service';

@Component({
  selector: 'app-cooking',
  standalone: true,
  imports: [],
  templateUrl: './cooking.component.html',
  styleUrl: './cooking.component.css'
})
export class CookingComponent {
  player = inject(PlayerService)

   //Cook a raw fish to a fish
   cookFish(/*idRawItem: number, idItem: number*/) {
    //this.player.addToInventory(idRawItem, -1)
    //this.player.addToInventory(idItem, 1)
    this.player.cookingLevel++
  }
}

<div>Cooking</div>
<div>Cooking level : {{player.cookingLevel}}</div>
<span class="p-2">
    <!-- <span class="p-1">You have {{ player.getNbItemInInventory(ItemId.RawFish) }} raw fish and {{ player.getNbItemInInventory(ItemId.Fish) }} fish</span> -->
    <!-- <button v-if="player.hasItemInInventory(ItemId.RawFish)" (click)="cookFish(ItemId.RawFish, ItemId.Fish)">Cook 1 fish</button> -->
    <button (click)="cookFish()">Cook 1 fish</button>
</span>
<span class="p-2">
    <!-- <span class="p-1" v-if="player.cookingLevel >= 5">You have {{ player.getNbItemInInventory(ItemId.RawCatfish) }} raw catfish and {{ player.getNbItemInInventory(ItemId.Catfish) }} catfish</span> -->
    <!-- <button v-if="player.cookingLevel >= 5 && player.hasItemInInventory(ItemId.RawCatfish)" (click)="cookFish(ItemId.RawCatfish, ItemId.Catfish)">Cook 1 catfish</button> -->
     @if (player.cookingLevel >= 5) {
        <button (click)="cookFish()">Cook 1 catfish</button>
     }
</span>

// MyMelvor/mymelvor.client/src/views/Cooking.vue
<script setup>
    import { player } from '../stores/player.js'
    import ItemId from "../classes/ItemId.js"

    function cookFish(idItem) {
        player.addToInventory(idItem, 1)
        player.cookingLevel++
    }
</script>

<template>
    <main>
        <div>Cooking.vue</div>
        <div>Cooking level :  {{player.cookingLevel}}</div>
        <button @click="cookFish(ItemId.Fish)">Cook 1 fish</button>
        <button v-if="player.cookingLevel >= 5" @click="cookFish(ItemId.Catfish)">Cook 1 catfish</button>
    </main>
</template>
