// MyMelvorNg/src/app/woodcutting/woodcutting.component.ts
import { Component, inject } from '@angular/core';
import { PlayerService } from '../player.service';

@Component({
  selector: 'app-woodcutting',
  standalone: true,
  imports: [],
  templateUrl: './woodcutting.component.html',
  styleUrl: './woodcutting.component.css'
})
export class WoodcuttingComponent {
  player = inject(PlayerService)

  cutWood(/*idItem: number*/) {
    //this.player.addToInventory(idItem, 1)
    this.player.woodcuttingLevel++
}
}

<div>Woodcutting</div>
<div>Woodcutting level :  {{player.woodcuttingLevel}}</div>
<span class="p-2">
    <!-- <span class="p-1">You have {{ player.getNbItemInInventory(ItemId.Wood) }} normal wood</span> -->
    <!-- <button @click="cutWood(ItemId.Wood)">Cut 1 normal log</button> -->
    <button (click)="cutWood()">Cut 1 normal log</button>
</span>
<span class="p-2">
    <!-- <span class="p-1" v-if="player.woodcuttingLevel >= 5">You have {{ player.getNbItemInInventory(ItemId.Teak) }} teak log</span> -->
    <!-- <button v-if="player.woodcuttingLevel >= 5" @click="cutWood(ItemId.Teak)">Cut 1 teak log</button> -->
     @if (player.woodcuttingLevel >= 5) {
        <button (click)="cutWood()">Cut 1 teak log</button>
     }
</span>

// MyMelvor/mymelvor.client/src/views/Woodcutting.vue
<script setup>
    import { player } from '../stores/player.js'
    import ItemId from "../classes/ItemId.js"

    function cutWood(idItem) {
        player.addToInventory(idItem, 1)
        player.woodcuttingLevel++
    }
</script>

<template>
    <main>
        <div>Woodcutting.vue</div>
        <div>Woodcutting level :  {{player.woodcuttingLevel}}</div>
        <button @click="cutWood(ItemId.Wood)">Cut 1 normal log</button>
        <button v-if="player.woodcuttingLevel >= 5" @click="cutWood(ItemId.Teak)">Cut 1 teak log</button>
    </main>
</template>
